### ISSUE TITLE
hey i cant make this a question lable sorry

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [SubtleXP/FNF-DUSTTALE-Web-Potato-Device#1]
but why dont you take a break on dusttale and move on to a another mod!

**Comment by SubtleXP** [comment]
I can’t just yet, this isn’t even finished! It still doesn’t work fully, and I gotta fix it, but I don’t got a lot of time everyday, and I’m gonna fix it this weekend then do the other mods

**Comment by LEVIXDDLMAO** [comment]
i was just sayin-

**Comment by LEVIXDDLMAO** [comment]
oh and one other thing when if you make  the tails.exe mod can you mention me? or somethin??

**Comment by SubtleXP** [comment]
You’ll be in the game files, and in the intro text
